# TODO: Parse XML
Parse XML into python processable data


## Parsing - Firdhan

In [42]:
import numpy as np
import pandas as pd
import nltk
import io
from google.colab import drive

drive.mount("/content/gdrive")


ModuleNotFoundError: No module named 'nltk'

In [ ]:
import xml.etree.ElementTree as et 

def parse_XML_unlabeled(xml_path, df_cols):
  xtree = et.parse(xml_path)
  xroot = xtree.getroot()

  rows = []
  for node in xroot:
    review = node.find(df_cols[0]).text if node is not None else None

    rows.append({f'{df_cols[0]}': review})
  
  out_df = pd.DataFrame(rows, columns = df_cols)
  return out_df

In [ ]:
testing_data_df = parse_XML_unlabeled('/content/gdrive/My Drive/sample data/testing_data.xml', ["review"])
testing_data_df

review
0      Berkunjung kesini karena baca review yang bila...
1      Nyam.. Bakut franchise dari Singapore ini ga p...
2      Saya makan disini kemarin makan bakwan malang....
3      Pertama liat agak aneh sih karna warnanya item...
4      A new addition to the Japanese-owned Sentral S...
...                                                  ...
14023  Tempatnya penuh terus setiap saya mampir kesin...
14024  Sambil jalan-jalan enaknya sambil makan ice cr...
14025  Kalau lagi mau makan rame-rame tapi bingung ma...
14026  Dulu sering banget nih kesini,mungkin hampir t...
14027  Pertama kali kesinii dlu pernahnya di mountain...

[14028 rows x 1 columns]

In [ ]:
unlabelled_df = parse_XML_unlabeled('/content/gdrive/My Drive/sample data/unlabelled_data.xml', ["review"])
unlabelled_df

review
0       Malabar mountain cafe, liat cafe ini sebenerny...
1       Gurame bakar enak, sotongnya enak, udang bakar...
2       Uda lama pengen coba kesini, kebetulan pas mau...
3       JJ Royal Bistro terletak di lantai LG Senayan ...
4       Makanannya enak2 overall, harga reasonable, po...
...                                                   ...
159021  Utk upnormal yg di Gading serpong ini tempatny...
159022  Ke sini pas lagi laper berat jadi nyari nasi b...
159023  Cobain mie goreng yg double pake sambel matah,...
159024  Sebenernya nyobain cafè bene yg pertama kali y...
159025  Enak & beda dr yg lain. \nHarganya jg ga terla...

[159026 rows x 1 columns]

## Parsing - Agung



In [ ]:
!pip install pandas==1.3.4

     |████████████████████████████████| 11.3 MB 5.2 MB/s 
  Attempting uninstall: pandas
    Found existing installation: pandas 1.1.5
    Uninstalling pandas-1.1.5:
      Successfully uninstalled pandas-1.1.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas~=1.1.0; python_version >= "3.0", but you have pandas 1.3.4 which is incompatible.


In [ ]:
# Necessary Import
import numpy as np
import pandas as pd
import nltk
import io

In [ ]:
# Optionally upload files
from google.colab import files
uploaded = files.upload()

In [ ]:
# XSL Stylesheet
style_string = '''
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:template match = "corpus">
  <reviews> 
  <xsl:for-each select="review">
    <review>
        <rid><xsl:value-of select="@rid"/></rid>
        <text><xsl:value-of select="text"/></text>  
        <xsl:for-each select="aspects[@id=0]">
          <food><xsl:value-of select="aspect[@category='FOOD']/@polarity"/></food>
          <ambience><xsl:value-of select="aspect[@category='AMBIENCE']/@polarity"/></ambience>
          <service><xsl:value-of select="aspect[@category='SERVICE']/@polarity"/></service>
          <price><xsl:value-of select="aspect[@category='PRICE']/@polarity"/></price>     
        </xsl:for-each>
    </review>
  </xsl:for-each>
</reviews>
</xsl:template > 
</xsl:stylesheet>
'''

xsl_style = io.StringIO(style_string)

In [ ]:
labelled_df = pd.read_xml("labelled_data_fixed.xml", stylesheet=xsl_style)
unlabelled_df = pd.read_xml("unlabelled_data.xml")
testing_df = pd.read_xml("testing_data.xml")

print(labelled_df)
print(unlabelled_df)
print(testing_df)

       rid  ...     price
0     1404  ...      None
1     3767  ...      None
2     2070  ...      None
3     1923  ...      None
4     1641  ...  NEGATIVE
...    ...  ...       ...
3860  3841  ...  NEGATIVE
3861  1353  ...  POSITIVE
3862  2911  ...      None
3863  2063  ...  POSITIVE
3864  3725  ...      None

[3865 rows x 6 columns]
         index                                             review
0        55569  Malabar mountain cafe, liat cafe ini sebenerny...
1       172797  Gurame bakar enak, sotongnya enak, udang bakar...
2       147762  Uda lama pengen coba kesini, kebetulan pas mau...
3       144971  JJ Royal Bistro terletak di lantai LG Senayan ...
4        68768  Makanannya enak2 overall, harga reasonable, po...
...        ...                                                ...
159021   19710  Utk upnormal yg di Gading serpong ini tempatny...
159022   63203  Ke sini pas lagi laper berat jadi nyari nasi b...
159023   25930  Cobain mie goreng yg double pake sambel matah,...
159

# TODO: Translate Review
Karena bahasa review nya ada inggris sama indonesia, gua rasa bisa di translate ke bahasa indonesia aja. Can use Google Translate python library

## Translation - Firdhan

In [ ]:
pip install langdetect


     |████████████████████████████████| 981 kB 7.6 MB/s 
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993242 sha256=a2ecd7f754d22222129ba2a86dd9a12ddf8e90e3c140a2930cfd897667bb1f81
  Stored in directory: /root/.cache/pip/wheels/c5/96/8a/f90c59ed25d75e50a8c10a1b1c2d4c402e4dacfa87f3aff36a
Successfully built langdetect


In [ ]:
from langdetect import detect

detect(testing_data_df['review'][0])

'id'

## Translation - Agung

In [ ]:
# Install requirements
!pip install langdetect
!pip install googletrans==4.0.0rc1

  Created wheel for googletrans: filename=googletrans-4.0.0rc1-py3-none-any.whl size=17415 sha256=9563dc9ab695c9279623c8a3618d984d3230d1a1b3a8e04f2893d4ba2a974ec0
  Stored in directory: /root/.cache/pip/wheels/43/34/00/4fe71786ea6d12314b29037620c36d857e5d104ac2748bf82a
Successfully built googletrans
  Attempting uninstall: googletrans
    Found existing installation: googletrans 3.1.0a0
    Uninstalling googletrans-3.1.0a0:
      Successfully uninstalled googletrans-3.1.0a0


In [ ]:
# Necessary Import
from googletrans import Translator
from langdetect import detect, LangDetectException

In [ ]:
# Translate english reviews to indonesian for consistency
translator = Translator()
translated_rows = []

for index, row in labelled_df.iterrows():
  try:
    if detect(row['text']) == 'en':
      translated = translator.translate(row["text"], src='en', dest='id')
      row['text'] = translated.text
      translated_rows.append(row)
    else:
      translated_rows.append(row)

  except LangDetectException:
    continue

labelled_translated_df = pd.DataFrame(translated_rows)

In [ ]:
# Save translated dataframe as csv, since translating process is long. Can 
# upload from file for next use
labelled_translated_df.to_csv('translated_labelled_data.csv')

/content


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# TODO: Stopword Removal dan Lemmatization
Use Sastrawi https://pypi.org/project/Sastrawi/


Sepertinya stopwword removal tidak perlu, karena beberapa stopword penting untuk konteks. (nggak dan tidak termasuk kedalam list stopword sastrawi, tapi penting untuk negasi kata)

In [ ]:
pip install Sastrawi

     |████████████████████████████████| 209 kB 5.2 MB/s 


In [ ]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

In [ ]:
# Optionally upload translated_labelled_data.csv
from google.colab import files

uploaded = files.upload()

labelled_translated_df = pd.read_csv('translated_labelled_data.csv')

In [ ]:
factory = StemmerFactory()
stemmer = factory.create_stemmer()

stemmed_rows = []
for index, row in labelled_translated_df.iterrows():
  stemmed = stemmer.stem(row['text'])
  row['text'] = stemmed
  stemmed_rows.append(row)

stemmed_df = pd.DataFrame(stemmed_rows)

In [ ]:
# Save translated dataframe as csv, since stemming process is long. Can 
# upload from file for next use
stemmed_df.to_csv('stemmed_labelled_data.csv')

# TODO: Tokenize

In [ ]:
# Optionally upload stemmed_labelled_data.csv
from google.colab import files

uploaded = files.upload()

stemmed_df = pd.read_csv('stemmed_labelled_data.csv')

NameError: ignored

In [ ]:
import nltk

In [ ]:
# Tokenize Stemmed Data
tokenized_rows = []

for index, row in stemmed_df.iterrows():
  tokenized = nltk.word_tokenize(row['text'])
  row['text'] = tokenized
  tokenized_rows.append(row)

tokenized_stemmed_df = pd.DataFrame(tokenized_rows)

In [ ]:
# Tokenize unstemmed data
tokenized_rows = []

for index, row in labelled_translated_df.iterrows():
  tokenized = nltk.word_tokenize(row['text'])
  row['text'] = tokenized
  tokenized_rows.append(row)

tokenized_df = pd.DataFrame(tokenized_rows)

# TODO: Method 1, ANN

Train 2 models. first model is aspect classifier. Second model is sentiment classifier with aspect + text as input. Alternatively, separate output into 4 tasks


In [1]:
!pip install transformers
!pip install -q -U tensorflow-text
!pip install -q tf-models-official

Defaulting to user installation because normal site-packages is not writeable


You should consider upgrading via the 'c:\program files\python39\python.exe -m pip install --upgrade pip' command.
You should consider upgrading via the 'c:\program files\python39\python.exe -m pip install --upgrade pip' command.
You should consider upgrading via the 'c:\program files\python39\python.exe -m pip install --upgrade pip' command.


In [1]:
import tensorflow as tf
from transformers import BertTokenizer, TFBertModel, TFBertForSequenceClassification
import pandas as pd
import numpy as np
import os

In [2]:
# Upload saved dataframes
# from google.colab import files

# uploaded = files.upload()

stemmed_df = pd.read_csv('stemmed_labelled_data.csv')
labelled_translated_df = pd.read_csv('translated_labelled_data.csv')

In [3]:
PRE_TRAINED_MODEL_NAME = 'cahya/bert-base-indonesian-522M'

tokenizer = BertTokenizer.from_pretrained(PRE_TRAINED_MODEL_NAME)

In [4]:
MAX_LEN = 200

In [5]:
# Tokenize text for input
tokenized_rows = []
tokenized_mask = []
for index, row in labelled_translated_df.iterrows():
  tokenized = tokenizer.encode_plus(row['text'], padding="max_length", truncation=True, return_tensors="tf", max_length=MAX_LEN, add_special_tokens=True) 
  tokenized_rows.append(tokenized['input_ids'])
  tokenized_mask.append(tokenized['attention_mask'])

tokenized_rows = np.array(tokenized_rows)
tokenized_mask = np.array(tokenized_mask)

In [6]:
# Prepare Label for output (one hot encode for each)
def encode_label(inp):
  if inp == "NEGATIVE":
    return [1,0,0]
  elif inp == "POSITIVE":
    return [0,0,1]
  else:
    return [0,1,0]

food_rows = []
ambi_rows = []
serv_rows = []
pric_rows = []
for index, row in labelled_translated_df.iterrows():
  food_rows.append(encode_label(row['food']))
  ambi_rows.append(encode_label(row['ambience']))
  serv_rows.append(encode_label(row['service']))
  pric_rows.append(encode_label(row['price']))

In [7]:
bert_model = TFBertModel.from_pretrained(PRE_TRAINED_MODEL_NAME, use_cache=False)

Some layers from the model checkpoint at cahya/bert-base-indonesian-522M were not used when initializing TFBertModel: ['mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at cahya/bert-base-indonesian-522M.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [8]:
input_ids_in = tf.keras.layers.Input(shape=(200,), name='input_token', dtype='int32')


X = bert_model(input_ids_in)[0]
# X = tf.keras.layers.Dense(128, activation='relu')(X)
X = tf.keras.layers.Flatten()(X)
X = tf.keras.layers.Dense(128)(X)
X = tf.keras.layers.Dropout(0.1)(X)
output_food = tf.keras.layers.Dense(3, activation='softmax')(X)
output_ambi = tf.keras.layers.Dense(3, activation='softmax')(X)
output_serv = tf.keras.layers.Dense(3, activation='softmax')(X)
output_pric = tf.keras.layers.Dense(3, activation='softmax')(X)

model = tf.keras.Model(inputs=input_ids_in, outputs = [output_food, output_ambi, output_serv, output_pric])

In [9]:
model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(learning_rate=0.00001), metrics=['accuracy'])
    

In [10]:
x_val1 = tf.reshape(tf.convert_to_tensor(tokenized_rows[-500:]), [-1,200])
x_val2 =  tf.reshape(tf.convert_to_tensor(tokenized_mask[-500:]), [-1,200])
y_food_v = tf.convert_to_tensor(food_rows[-500:])
y_ambi_v = tf.convert_to_tensor(ambi_rows[-500:])
y_serv_v = tf.convert_to_tensor(serv_rows[-500:])
y_pric_v = tf.convert_to_tensor(pric_rows[-500:])
x_train1 = tf.reshape(tf.convert_to_tensor(tokenized_rows[:-500]), [-1,200])
x_train2 = tf.reshape(tf.convert_to_tensor(tokenized_mask[:-500]), [-1,200])
y_food_t = tf.convert_to_tensor(food_rows[:-500])
y_ambi_t = tf.convert_to_tensor(ambi_rows[:-500])
y_serv_t = tf.convert_to_tensor(serv_rows[:-500])
y_pric_t = tf.convert_to_tensor(pric_rows[:-500])

In [11]:
NUM_EPOCHS = 3

history = model.fit(x_train1, [y_food_t, y_ambi_t, y_serv_t, y_pric_t], epochs=NUM_EPOCHS, validation_data=(x_val1, [y_food_v, y_ambi_v, y_serv_v, y_pric_v]), batch_size=1)

Epoch 1/3
3364/3364 [==============================] - 2146s 633ms/step - loss: 8.2615 - dense_1_loss: 1.6884 - dense_2_loss: 2.5496 - dense_3_loss: 1.8993 - dense_4_loss: 2.1242 - dense_1_accuracy: 0.7140 - dense_2_accuracy: 0.5568 - dense_3_accuracy: 0.6754 - dense_4_accuracy: 0.6629 - val_loss: 6.4937 - val_dense_1_loss: 1.1936 - val_dense_2_loss: 2.1407 - val_dense_3_loss: 1.7594 - val_dense_4_loss: 1.4000 - val_dense_1_accuracy: 0.7600 - val_dense_2_accuracy: 0.6400 - val_dense_3_accuracy: 0.6060 - val_dense_4_accuracy: 0.7100
Epoch 2/3
3364/3364 [==============================] - 2140s 636ms/step - loss: 2.6659 - dense_1_loss: 0.5821 - dense_2_loss: 0.9249 - dense_3_loss: 0.5881 - dense_4_loss: 0.5708 - dense_1_accuracy: 0.8466 - dense_2_accuracy: 0.7880 - dense_3_accuracy: 0.8555 - dense_4_accuracy: 0.8659 - val_loss: 6.8954 - val_dense_1_loss: 1.1144 - val_dense_2_loss: 2.9669 - val_dense_3_loss: 1.3753 - val_dense_4_loss: 1.4387 - val_dense_1_accuracy: 0.7880 - val_dense_2_acc

In [19]:
# test_input = "makanan di restoran ini enak banget, harus coba cheeseburger nya. Soda yang ditawarin juga banyak banget"
test_input = "Restoran ini kotor dan tidak terurus. Sepi banget, ga rekomen"

tokenized_test = tokenizer.__call__(test_input, padding="max_length", truncation=True, return_tensors="tf", max_length=MAX_LEN) 
test_id = tokenized_test['input_ids']
test_mask = tokenized_test['attention_mask']

x_test1 = tf.reshape(tf.convert_to_tensor(test_id), [-1,200])
x_test2 =  tf.reshape(tf.convert_to_tensor(test_mask), [-1,200])

result = model(x_test1)
print(result)

# [<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.87806886, 0.0897361 , 0.03219494]], dtype=float32)>, <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.10894261, 0.8562767 , 0.03478076]], dtype=float32)>, <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.01104022, 0.98246497, 0.00649487]], dtype=float32)>, <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.01104022, 0.98246497, 0.00649487]], dtype=float32)>]

[<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.00597906, 0.952412  , 0.04160893]], dtype=float32)>, <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.07020407, 0.8830153 , 0.0467806 ]], dtype=float32)>, <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.03246272, 0.9321489 , 0.03538837]], dtype=float32)>, <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.00692535, 0.8376694 , 0.1554053 ]], dtype=float32)>]


In [27]:

tf.keras.models.save_model(model, "firstmodel")

INFO:tensorflow:Assets written to: firstmodel\assets


INFO:tensorflow:Assets written to: firstmodel\assets
C:\Users\MRAP\AppData\Roaming\Python\Python39\site-packages\keras\utils\generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '


In [32]:
tf.keras.models.load_model("firstmodel")

ResourceExhaustedError: OOM when allocating tensor with shape[768,768] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:Fill]

In [14]:
!pip install langdetect
!pip install googletrans==4.0.0rc1
!pip install pandas==1.3.4
!pip install lxml

Defaulting to user installation because normal site-packages is not writeable


You should consider upgrading via the 'c:\program files\python39\python.exe -m pip install --upgrade pip' command.


Defaulting to user installation because normal site-packages is not writeable


You should consider upgrading via the 'c:\program files\python39\python.exe -m pip install --upgrade pip' command.


Defaulting to user installation because normal site-packages is not writeable

You should consider upgrading via the 'c:\program files\python39\python.exe -m pip install --upgrade pip' command.



Defaulting to user installation because normal site-packages is not writeable


You should consider upgrading via the 'c:\program files\python39\python.exe -m pip install --upgrade pip' command.


In [15]:
# Necessary Import
from googletrans import Translator
from langdetect import detect, LangDetectException
import pandas as pd

In [16]:
# Create inferrence function

def infer(text) :
    translator = Translator()
    translated = ''
    try:
        if detect(text) == 'en':
            translated = translator.translate(text, src='en', dest='id')
            translated = translated.text.lower()
        else:
            translated = text.lower()

    except LangDetectException:
        translated = text.lower()

    PRE_TRAINED_MODEL_NAME = 'cahya/bert-base-indonesian-522M'

    tokenizer = BertTokenizer.from_pretrained(PRE_TRAINED_MODEL_NAME)

    tokenized_test = tokenizer.__call__(text, padding="max_length", truncation=True, return_tensors="tf", max_length=200) 
    test_id = tokenized_test['input_ids']
    test_mask = tokenized_test['attention_mask']

    x_test1 = tf.reshape(tf.convert_to_tensor(test_id), [-1,200])
    x_test2 =  tf.reshape(tf.convert_to_tensor(test_mask), [-1,200])

    result = model(x_test1)

    return result

In [17]:
# Parse test xml
print(pd.__version__)
testing_df = pd.read_xml("testing_data.xml")

1.3.4


In [21]:
threshold = 0.5

test_result = []
for index, row in testing_df.iterrows():
  text = row['review']
  inferred_result = infer(text)

  result = [index]

  for i in inferred_result:
    if i[0][2] == max(i[0]):
      result.append("POSITIVE")
    elif i[0][0] == max(i[0]):
      result.append("NEGATIVE")
    else:
      result.append("-")
 
  test_result.append(result)

In [25]:
import csv


with open("result.csv","w+", newline='') as my_csv:
    csvWriter = csv.writer(my_csv,delimiter=',')
    csvWriter.writerows(test_result)

# TODO: Method 2, Naive Bayes

# TODO: (OPTIONAL) Semi supervised labelling on unlabelled data
